export const CAST = {
  lyen: {
    id: "lyen",
    player: true,
    name: { ar: "ليان آل فارِث", en: "Lyen al-Vareth" },
    title: { ar: "الوريث المنفي", en: "The Exiled Heir" },
    portrait: "assets/art/hero.png",
    color: "#d4c4a0",
    speed: 2.35,
  },
  runa: {
    id: "runa",
    name: { ar: "النقيبة رونا", en: "Captain Runa" },
    title: { ar: "حارسة الميناء", en: "Harbor Watch" },
    portrait: "assets/art/runa.png",
    color: "#c47a4a",
  },
  maia: {
    id: "maia",
    name: { ar: "مايا", en: "Maia" },
    title: { ar: "صاحبة الفانوس الأخير", en: "Innkeeper" },
    portrait: null,
    color: "#e0b070",
  },
  orlen: {
    id: "orlen",
    name: { ar: "الكاتب أورلن", en: "Scribe Orlen" },
    title: { ar: "حافظ الأرشيف", en: "Archive Keeper" },
    portrait: null,
    color: "#a8b8c8",
  },
  serath: {
    id: "serath",
    name: { ar: "الملكة سيراث", en: "Queen-widow Serath" },
    title: { ar: "الأرملة المتوّجة", en: "The Crowned Widow" },
    portrait: null,
    color: "#e8dcc8",
  },
  pharos: {
    id: "pharos",
    name: { ar: "المستشار فاروس", en: "Chancellor Pharos" },
    title: { ar: "خاتم المجلس", en: "Seal of the Council" },
    portrait: "assets/art/pharos.png",
    color: "#c9a227",
  },
  aldric: {
    id: "aldric",
    name: { ar: "ظل ألدريك", en: "Shade of Aldric" },
    title: { ar: "الملك الراحل", en: "The Late King" },
    portrait: null,
    color: "#9ad0e0",
  },
  theWill: {
    id: "theWill",
    name: { ar: "الوصية", en: "The Will" },
    title: { ar: "الإرادة الجائعة", en: "The Hungry Testament" },
    portrait: "assets/art/will.png",
    color: "#e8d48a",
  },
  guardian: {
    id: "guardian",
    name: { ar: "ختم الظل", en: "Shadow Seal" },
    title: { ar: "حارس المزور", en: "Forgery's Guard" },
    portrait: null,
    color: "#6a3040",
  },
};
