import { TILE } from "../game/layers.js";

export const PLACE_DEFS = [
  {
    id: "harbor",
    name: { ar: "ميناء الرماد", en: "Ash Harbor" },
    chapter: 1,
    art: "assets/art/harbor.png",
    ambient: "harbor",
    w: 48,
    h: 32,
    spawn: { x: 10, y: 22 },
    biome: "ash",
    weather: "ashfall",
    camera: { zoom: 1, shake: 0, letterbox: 0 },
    lights: [
      { x: 12, y: 20, r: 5, c: "#ffb060", a: 0.45 },
      { x: 24, y: 16, r: 4, c: "#ff9040", a: 0.35 },
      { x: 36, y: 18, r: 6, c: "#e8c070", a: 0.4 },
    ],
    audioZones: [{ id: "docks", x: 6, y: 24, w: 16, h: 6, cue: "waves" }],
  },
  {
    id: "inn",
    name: { ar: "الفانوس الأخير", en: "The Last Lantern" },
    chapter: 1,
    art: "assets/art/inn.png",
    ambient: "inn",
    w: 28,
    h: 20,
    spawn: { x: 14, y: 16 },
    biome: "wood",
    weather: "none",
    camera: { zoom: 1.15, shake: 0, letterbox: 0 },
    lights: [
      { x: 14, y: 8, r: 8, c: "#ffcc77", a: 0.55 },
      { x: 6, y: 10, r: 4, c: "#ffaa55", a: 0.3 },
    ],
    audioZones: [{ id: "hearth", x: 10, y: 6, w: 8, h: 6, cue: "fire" }],
  },
  {
    id: "moors",
    name: { ar: "المستنقعات الهامسة", en: "Whispering Moors" },
    chapter: 2,
    art: "assets/art/moors.png",
    ambient: "moors",
    w: 56,
    h: 36,
    spawn: { x: 8, y: 30 },
    biome: "moor",
    weather: "mist",
    camera: { zoom: 0.92, shake: 0, letterbox: 0 },
    lights: [
      { x: 28, y: 16, r: 3, c: "#88c0d0", a: 0.25 },
      { x: 40, y: 20, r: 4, c: "#a0e0c0", a: 0.2 },
    ],
    audioZones: [{ id: "stones", x: 24, y: 12, w: 12, h: 10, cue: "whisper" }],
  },
  {
    id: "watch",
    name: { ar: "المرقب الخرب", en: "Ruined Watch" },
    chapter: 2,
    art: "assets/art/moors.png",
    ambient: "moors",
    w: 24,
    h: 22,
    spawn: { x: 12, y: 18 },
    biome: "stone",
    weather: "mist",
    camera: { zoom: 1.1, shake: 0, letterbox: 0 },
    lights: [{ x: 12, y: 8, r: 5, c: "#c0d8e8", a: 0.3 }],
    audioZones: [],
  },
  {
    id: "court",
    name: { ar: "البلاط المزور", en: "The Forged Court" },
    chapter: 3,
    art: "assets/art/court.png",
    ambient: "court",
    w: 44,
    h: 30,
    spawn: { x: 22, y: 26 },
    biome: "marble",
    weather: "none",
    camera: { zoom: 1, shake: 0, letterbox: 0.04 },
    lights: [
      { x: 22, y: 8, r: 7, c: "#e8d090", a: 0.4 },
      { x: 10, y: 14, r: 4, c: "#d0c8b0", a: 0.25 },
      { x: 34, y: 14, r: 4, c: "#d0c8b0", a: 0.25 },
    ],
    audioZones: [{ id: "hall", x: 16, y: 6, w: 12, h: 10, cue: "hall" }],
  },
  {
    id: "archives",
    name: { ar: "أرشيف المجلس", en: "Council Archives" },
    chapter: 3,
    art: "assets/art/vault.png",
    ambient: "archive",
    w: 32,
    h: 24,
    spawn: { x: 16, y: 20 },
    biome: "stone",
    weather: "none",
    camera: { zoom: 1.08, shake: 0, letterbox: 0 },
    lights: [
      { x: 8, y: 10, r: 4, c: "#d4b060", a: 0.35 },
      { x: 24, y: 10, r: 4, c: "#d4b060", a: 0.35 },
    ],
    audioZones: [],
  },
  {
    id: "vault",
    name: { ar: "قبو الوصايا", en: "Vault of Wills" },
    chapter: 4,
    art: "assets/art/vault.png",
    ambient: "vault",
    w: 40,
    h: 28,
    spawn: { x: 6, y: 24 },
    biome: "vault",
    weather: "dust",
    camera: { zoom: 1, shake: 0, letterbox: 0.06 },
    lights: [
      { x: 20, y: 12, r: 8, c: "#70e0c8", a: 0.4 },
      { x: 32, y: 16, r: 4, c: "#e8c060", a: 0.3 },
    ],
    audioZones: [{ id: "seal", x: 16, y: 8, w: 10, h: 8, cue: "hum" }],
  },
  {
    id: "throne",
    name: { ar: "العرش الأجوف", en: "The Hollow Throne" },
    chapter: 5,
    art: "assets/art/court.png",
    ambient: "finale",
    w: 36,
    h: 26,
    spawn: { x: 18, y: 22 },
    biome: "marble",
    weather: "embers",
    camera: { zoom: 1.05, shake: 0, letterbox: 0.1 },
    lights: [
      { x: 18, y: 8, r: 9, c: "#ffd070", a: 0.5 },
      { x: 18, y: 14, r: 5, c: "#ff6060", a: 0.25 },
    ],
    audioZones: [{ id: "throne", x: 14, y: 4, w: 8, h: 8, cue: "choir" }],
  },
];

export const PLACE_IDS = PLACE_DEFS.map((p) => p.id);

export function placeById(id) {
  return PLACE_DEFS.find((p) => p.id === id);
}
